//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace COTODAMA_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int ID { get; set; }
        public string ItemId { get; set; }
        public string ItemName { get; set; }
        public string ItemDiscription { get; set; }
        public int ItemPriceUnit { get; set; }
        public int ItemLengthMin { get; set; }
        public int ItemLengthMax { get; set; }
        public int CategoryId { get; set; }
        public Nullable<System.DateTime> ItemDeliveryDate { get; set; }
        public Nullable<int> ItemStock { get; set; }
        public System.DateTime RegisterDateTime { get; set; }
        public System.DateTime EditDateTime { get; set; }
    }
}
