//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace COTODAMA_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Member
    {
        public string MemberPref { get; set; }
        public string MemberAddress { get; set; }
        public string MemberPhone { get; set; }
        public System.DateTime MemberBirth { get; set; }
        public string MemberFirstName { get; set; }
        public string MemberLastName { get; set; }
        public string MemberFirstNameKana { get; set; }
        public string MemberLastNameKana { get; set; }
        public string CompanyName { get; set; }
        public string CompanyPostNumber { get; set; }
        public string CompanyAddress { get; set; }
        public string MemberPostNumber { get; set; }
        public string BankNumber { get; set; }
        public string BankBranchNumber { get; set; }
        public string BankAccountNumber { get; set; }
        public string HundleName { get; set; }
        public string BankAccountName { get; set; }
        public string IconFilepath { get; set; }
        public System.DateTime RegisterDateTime { get; set; }
        public System.DateTime EditDateTime { get; set; }
        public int MemberID { get; set; }
        public string TokenID { get; set; }
        public string TalentComment { get; set; }
        public string TwitterURL { get; set; }
        public string InstaURL { get; set; }
        public string FBURL { get; set; }
        public string MemberEmail { get; set; }
        public string Password { get; set; }
        public int ItemID { get; set; }
        public bool IsSeller { get; set; }
    }
}
