//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace COTODAMA_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cotodamaEntities : DbContext
    {
        public cotodamaEntities()
            : base("name=cotodamaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<M_Item> M_Item { get; set; }
        public virtual DbSet<M_Member> M_Member { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<M_Category> M_Category { get; set; }
        public virtual DbSet<T_Order> T_Order { get; set; }
        public virtual DbSet<T_Sample> T_Sample { get; set; }
        public virtual DbSet<T_QuestionOfItem> T_QuestionOfItem { get; set; }
        public virtual DbSet<T_QuestionOfOrder> T_QuestionOfOrder { get; set; }
        public virtual DbSet<T_Sale> T_Sale { get; set; }
    }
}
