//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace COTODAMA_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QuestionOfOrder
    {
        public int QuestionID { get; set; }
        public string QuestionName { get; set; }
        public string AnswerName { get; set; }
        public int ItemID { get; set; }
        public int OrderID { get; set; }
        public int SortID { get; set; }
        public System.DateTime RegisterDateTime { get; set; }
        public System.DateTime EditDateTime { get; set; }
        public int SellerID { get; set; }
        public int OrdererID { get; set; }
    }
}
